version: "3.7"
services:
  centos:
    container_name: centos
    restart: always
    build:
      context: .
      dockerfile: centos-dev.Dockerfile
    environment:
      - ABC=123
      # - AWS_PROFILE=tss_dev
      # - FLASK_SECRET_KEY
      # - JWT_HEADER=X-Pomerium-Jwt-Assertion
      # - JWT_SIGNING_CERT
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ~/.aws:/root/.aws/:ro
      - ./test/config.conf:/usr/local/etc/journald.conf
      # - /usr/local/etc/journald-cloudwatch-logs.conf
